#!/usr/bin/env bash
# shellcheck shell=bash
# ==============================================================================
# 35-instructions (design D12/D14): generate each agent's global instruction file
# from the bundled guidance (/opt/paseo-ha/AGENTS.base.md) plus the user's shared
# instructions (/config/AGENTS.md). The generated files live under /data and are
# rewritten on every start.
# ==============================================================================

PASEO_HA_CONFIG_DIR="${PASEO_HA_CONFIG_DIR:-/config}"
base_file="${PASEO_HA_OPT_DIR}/AGENTS.base.md"
user_file="${PASEO_HA_CONFIG_DIR}/AGENTS.md"

ph_render_instructions() {
  cat <<EOF
<!--
  GENERATED by the Paseo Home Assistant add-on on every start. Do not edit this file:
  changes are overwritten. Edit ${user_file} (addon_configs/<id>_paseo/AGENTS.md in
  File Editor/Samba) instead, then restart the add-on.
-->

EOF
  if [[ -f "${base_file}" ]]; then
    cat "${base_file}"
    echo
  fi
  if [[ -s "${user_file}" ]]; then
    echo
    echo "# User instructions (from ${user_file})"
    echo
    cat "${user_file}"
    echo
  fi
}

ph_write_instructions() {
  local content target tmp
  content="$(ph_render_instructions)"
  local targets=(
    "${CLAUDE_CONFIG_DIR:-${HOME}/.claude}/CLAUDE.md"
    "${CODEX_HOME:-${HOME}/.codex}/AGENTS.md"
    "${XDG_CONFIG_HOME:-${HOME}/.config}/opencode/AGENTS.md"
    "${PI_CODING_AGENT_DIR:-${HOME}/.pi/agent}/AGENTS.md"
  )
  for target in "${targets[@]}"; do
    mkdir -p "$(dirname "${target}")"
    # Replace a symlink instead of writing through it.
    [[ -L "${target}" ]] && rm -f "${target}"
    tmp="${target}.paseo-ha.tmp"
    printf '%s\n' "${content}" > "${tmp}" && mv -f "${tmp}" "${target}"
  done
  ph_log_info "Generated agent instruction files from AGENTS.base.md + ${user_file}"
}

ph_write_instructions
