#!/usr/bin/env bash
# shellcheck shell=bash
# ==============================================================================
# 47-git-auth (add-git-auth): give agents git access without prompts.
# - ~/.ssh is persistent: ssh and ssh-keygen resolve "~" from the passwd entry
#   (/root), not $HOME, so /root/.ssh is linked to /data/home/.ssh.
# - GitHub over HTTPS: gh is git's credential helper for github.com and
#   gist.github.com, unless the user configured a helper for them.
# - SSH: unencrypted private keys in /homeassistant/.ssh and /share/.ssh are
#   offered by ssh (referenced in place, never copied). Keys readable by others
#   are chmod 600'd; passphrase-protected keys are skipped with a warning.
# - Host keys: bundled github/gitlab/bitbucket keys plus known_hosts files next to
#   the discovered keys; unknown hosts are accepted on first use and remembered.
# - The generated /etc/ssh/ssh_config.d/paseo-ha.conf is rebuilt on every start;
#   the user's ~/.ssh/config is read first and wins.
# Key contents and tokens are never logged.
# ==============================================================================

PH_SSH_DIR="${HOME:-/data/home}/.ssh"
PH_SSH_ROOT_LINK="${PASEO_HA_SSH_ROOT_LINK:-/root/.ssh}"
PH_SSH_DROPIN="${PASEO_HA_SSH_DROPIN:-/etc/ssh/ssh_config.d/paseo-ha.conf}"
PH_SSH_KNOWN_HOSTS="${PASEO_HA_OPT_DIR}/ssh_known_hosts"
read -r -a PH_SSH_KEY_DIRS <<<"${PASEO_HA_SSH_KEY_DIRS:-/homeassistant/.ssh /share/.ssh}"
PH_GH_BIN="${PASEO_HA_GH_BIN:-/usr/local/bin/gh}"

ph_ssh_home() {
  mkdir -p "${PH_SSH_DIR}" && chmod 700 "${PH_SSH_DIR}"
  if [[ -L "${PH_SSH_ROOT_LINK}" ]]; then
    [[ "$(readlink "${PH_SSH_ROOT_LINK}")" == "${PH_SSH_DIR}" ]] && return 0
    rm -f "${PH_SSH_ROOT_LINK}"
  elif [[ -d "${PH_SSH_ROOT_LINK}" ]]; then
    # Only the image or an earlier session in this container could have made it.
    if cp -an "${PH_SSH_ROOT_LINK}/." "${PH_SSH_DIR}/" 2>/dev/null; then
      rm -rf "${PH_SSH_ROOT_LINK}"
    else
      ph_log_warn "Git access: could not move ${PH_SSH_ROOT_LINK} to ${PH_SSH_DIR}; leaving it in place"
      return 0
    fi
  fi
  mkdir -p "$(dirname "${PH_SSH_ROOT_LINK}")"
  ln -s "${PH_SSH_DIR}" "${PH_SSH_ROOT_LINK}"
}

ph_git_credential_helper() {
  local host
  [[ -x "${PH_GH_BIN}" ]] || return 0
  for host in https://github.com https://gist.github.com; do
    if [[ -z "$(git config --global --get-all "credential.${host}.helper" 2>/dev/null)" ]]; then
      git config --global --add "credential.${host}.helper" ""
      git config --global --add "credential.${host}.helper" "!${PH_GH_BIN} auth git-credential"
    fi
  done
}

# ph_is_private_key <file> -> 0 when the first line is a PEM/OpenSSH private key header.
ph_is_private_key() {
  local first
  IFS= read -r first < "$1" 2>/dev/null || return 1
  [[ "${first%$'\r'}" =~ ^-----BEGIN\ ([A-Z0-9]+\ )?PRIVATE\ KEY-----$ ]]
}

# Fills PH_SSH_KEYS and PH_SSH_HOSTFILES.
ph_ssh_discover() {
  local dir f mode
  PH_SSH_KEYS=()
  PH_SSH_HOSTFILES=()
  for dir in "${PH_SSH_KEY_DIRS[@]}"; do
    [[ -d "${dir}" ]] || continue
    [[ -f "${dir}/known_hosts" ]] && PH_SSH_HOSTFILES+=("${dir}/known_hosts")
    while IFS= read -r f; do
      ph_is_private_key "${f}" || continue
      mode="$(stat -c '%a' "${f}" 2>/dev/null)"
      if [[ -n "${mode}" && "${mode: -2}" != "00" ]]; then
        if chmod 600 "${f}" 2>/dev/null; then
          ph_log_info "Git access: restricted permissions of ${f} to 600 (was ${mode}) so ssh accepts it"
        else
          ph_log_warn "Git access: ${f} is readable by others (${mode}) and could not be changed; ssh will refuse it"
          continue
        fi
      fi
      if ! ssh-keygen -y -P '' -f "${f}" >/dev/null 2>&1; then
        ph_log_warn "Git access: skipping ${f}: it needs a passphrase (or is not a valid key), which agents cannot enter"
        continue
      fi
      PH_SSH_KEYS+=("${f}")
    done < <(find "${dir}" -mindepth 1 -maxdepth 1 -type f ! -name '*.pub' 2>/dev/null | LC_ALL=C sort)
  done
  if (( ${#PH_SSH_KEYS[@]} > 5 )); then
    ph_log_info "Git access: ${#PH_SSH_KEYS[@]} SSH keys found; servers usually allow about 6 attempts, so pin a key per host with IdentityFile in ${PH_SSH_DIR}/config"
  fi
}

ph_ssh_write_config() {
  local k n
  mkdir -p "$(dirname "${PH_SSH_DROPIN}")"
  {
    echo "# Generated by the Paseo add-on on every start; do not edit."
    echo "# Put your own settings in ${PH_SSH_DIR}/config, which is read first and wins."
    echo "Host *"
    for n in id_rsa id_ecdsa id_ecdsa_sk id_ed25519 id_ed25519_sk; do
      echo "  IdentityFile ${PH_SSH_DIR}/${n}"
    done
    for k in "${PH_SSH_KEYS[@]}"; do
      echo "  IdentityFile \"${k}\""
    done
    echo "  GlobalKnownHostsFile ${PH_SSH_KNOWN_HOSTS}${PH_SSH_HOSTFILES[*]:+ ${PH_SSH_HOSTFILES[*]}}"
    echo "  UserKnownHostsFile ${PH_SSH_DIR}/known_hosts"
    echo "  StrictHostKeyChecking accept-new"
    echo "  BatchMode yes"
  } > "${PH_SSH_DROPIN}.tmp" && mv -f "${PH_SSH_DROPIN}.tmp" "${PH_SSH_DROPIN}"
}

# Offline: report a token from the environment or the account in gh's hosts.yml.
ph_gh_status() {
  local user
  if [[ ! -x "${PH_GH_BIN}" ]]; then echo "GitHub CLI not installed"; return; fi
  if [[ -n "${GH_TOKEN:-}" ]]; then echo "GitHub CLI uses a token from GH_TOKEN"; return; fi
  if [[ -n "${GITHUB_TOKEN:-}" ]]; then echo "GitHub CLI uses a token from GITHUB_TOKEN"; return; fi
  user="$(timeout 10 "${PH_GH_BIN}" config get -h github.com user 2>/dev/null)"
  if [[ -n "${user}" ]]; then echo "GitHub CLI signed in as ${user}"; else echo "GitHub CLI not signed in (run gh auth login in a Paseo terminal)"; fi
}

ph_git_auth() {
  local keys=""
  ph_ssh_home
  ph_git_credential_helper
  ph_ssh_discover
  ph_ssh_write_config
  local own
  for own in "${PH_SSH_DIR}"/id_rsa "${PH_SSH_DIR}"/id_ecdsa "${PH_SSH_DIR}"/id_ecdsa_sk "${PH_SSH_DIR}"/id_ed25519 "${PH_SSH_DIR}"/id_ed25519_sk; do
    [[ -f "${own}" ]] && keys+="${keys:+, }${own}"
  done
  for own in "${PH_SSH_KEYS[@]}"; do keys+="${keys:+, }${own}"; done
  ph_log_info "Git access: SSH keys ${keys:-none}; $(ph_gh_status)"
}

ph_git_auth
